/* Sabuj Computers — Prompt Center, Templates & PWA */
(()=>{
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),day=()=>new Date().toISOString().slice(0,10);
const cats=['সব','NID','চাকরি','ছবি','CV','আবেদন','অন্যান্য'];
const templates=[['NID Download','NID','NID Download + Print + Lamination কাজের checklist ও customer details নেওয়ার template।'],['চাকরির আবেদন','চাকরি','প্রাপক, বিষয়, আবেদনকারীর তথ্য ও সংযুক্তির ready structure।'],['Passport Photo','ছবি','ছবি crop, background, resize, print ও delivery checklist।'],['Professional CV','CV','ATS-friendly CV তৈরির তথ্য সংগ্রহের template।'],['সাধারণ আবেদনপত্র','আবেদন','তারিখ, প্রাপক, বিষয়, মূল বক্তব্য ও আবেদনকারীর তথ্যের ready format।'],['Customer Work Order','অন্যান্য','Customer name, phone, কাজ, delivery date, amount ও note নেওয়ার quick form।']];
function notify(s){if(typeof toast==='function')toast(s);else alert(s)}
async function savePrompt(p){const id=p.id||crypto.randomUUID(),obj={title:p.title,text:p.text,category:p.category||'অন্যান্য',favorite:!!p.favorite,usedAt:p.usedAt||null},r=await db.from('workdesk_items').upsert({id,owner_id:me.id,item_type:'prompts',data:obj,updated_at:new Date().toISOString()});if(r.error)return notify(r.error.message);data.prompts=data.prompts||[];const i=data.prompts.findIndex(x=>x.id===id),v={id,...obj};i<0?data.prompts.unshift(v):data.prompts[i]=v;return v}
function promptUI(){const sec=$('prompts'),card=sec?.querySelector('.card');if(!card||card.dataset.pro2)return;card.dataset.pro2='1';const old=card.querySelector('.toolbar'),bar=document.createElement('div');bar.id='proPromptBar';bar.className='quick';bar.innerHTML=cats.map(c=>`<button type="button" data-cat="${c}">${c}</button>`).join('')+'<button type="button" data-cat="__fav">⭐ Favorites</button><button type="button" data-cat="__recent">🕘 Recent</button>';old?.after(bar);bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{bar.querySelectorAll('button').forEach(x=>x.classList.remove('g'));b.classList.add('g');renderPromptsPro(b.dataset.cat)});renderPromptsPro('সব')}
function renderPromptsPro(filter='সব'){const list=$('pl');if(!list)return;const q=($('ps')?.value||'').toLowerCase(),arr=(data.prompts||[]).filter(p=>(String(p.title||'')+' '+String(p.text||'')+' '+String(p.category||'')).toLowerCase().includes(q)).filter(p=>filter==='সব'||(filter==='__fav'?p.favorite:(filter==='__recent'?p.usedAt:p.category===filter)));list.innerHTML=arr.map(p=>`<div class="row"><div><b>${esc(p.title||'Untitled')}</b><small><span class="badge">${esc(p.category||'অন্যান্য')}</span> ${p.favorite?'⭐':''}</small><small>${esc(String(p.text||'').slice(0,180))}</small></div><div class="proactions"><button class="btn g" onclick="window.proUsePrompt('${esc(p.id)}')">⚡ Use</button><button class="btn l" onclick="window.proFavPrompt('${esc(p.id)}')">${p.favorite?'★':'☆'}</button><button class="btn l" onclick="window.proCopyPrompt('${esc(p.id)}')">Copy</button><button class="btn l" onclick="modal('prompt',data.prompts.find(x=>x.id==='${esc(p.id)}'))">Edit</button><button class="btn r" onclick="del('prompts','${esc(p.id)}')">Delete</button></div></div>`).join('')||'<div class="empty">Prompt নেই</div>'}
async function proFavPrompt(id){const p=(data.prompts||[]).find(x=>x.id===id);if(!p)return;await savePrompt({...p,favorite:!p.favorite});renderPromptsPro(document.querySelector('#proPromptBar .g')?.dataset.cat||'সব')}
async function proUsePrompt(id){const p=(data.prompts||[]).find(x=>x.id===id);if(!p)return;try{await navigator.clipboard.writeText(p.text||'');notify('Prompt copied')}catch(e){notify('Copy করা যায়নি')}await savePrompt({...p,usedAt:new Date().toISOString()});renderPromptsPro(document.querySelector('#proPromptBar .g')?.dataset.cat||'সব')}
async function proCopyPrompt(id){const p=(data.prompts||[]).find(x=>x.id===id);if(!p)return;try{await navigator.clipboard.writeText(p.text||'');notify('Copied')}catch(e){notify('Copy করা যায়নি')}}
function templateUI(){const host=$('tmpl');if(!host)return;host.parentElement.innerHTML='<div class="toolbar"><input id="tmplSearch" placeholder="Template খুঁজুন" oninput="window.renderTemplatesPro()"><button class="btn g" onclick="window.proTemplateForm()">＋ Custom Template</button></div><div id="tmplPro" class="templateGrid"></div>';renderTemplatesPro()}
function renderTemplatesPro(){const host=$('tmplPro');if(!host)return;const q=($('tmplSearch')?.value||'').toLowerCase(),custom=(data.templates||[]).map(t=>({name:t.title||t.name||'Custom Template',cat:t.category||'Custom',text:t.text||t.content||''})),arr=[...templates.map(x=>({name:x[0],cat:x[1],text:x[2],fixed:true})),...custom].filter(t=>(t.name+' '+t.cat+' '+t.text).toLowerCase().includes(q));host.innerHTML=arr.map(t=>`<div class="templateItem"><b>${esc(t.name)}</b><div class="muted">${esc(t.cat)}</div><p>${esc(t.text)}</p><div class="proactions"><button class="btn g" onclick="window.proCopyText('${esc(encodeURIComponent(t.text))}')">⚡ Use / Copy</button></div></div>`).join('')}
function proCopyText(s){try{navigator.clipboard.writeText(decodeURIComponent(s));notify('Template copied')}catch(e){notify('Copy করা যায়নি')}}
function proTemplateForm(){const title=prompt('Template name?');if(!title)return;const text=prompt('Template content?');if(text===null)return;const cat=prompt('Category?','অন্যান্য')||'অন্যান্য';saveTemplate({title,text,category:cat})}
async function saveTemplate(o){const id=crypto.randomUUID(),r=await db.from('workdesk_items').insert({id,owner_id:me.id,item_type:'templates',data:o,updated_at:new Date().toISOString()});if(r.error)return notify(r.error.message);data.templates=data.templates||[];data.templates.unshift({id,...o});notify('Template saved');renderTemplatesPro()}
function pwa(){let link=document.querySelector('link[rel="manifest"]');if(!link){link=document.createElement('link');link.rel='manifest';link.href='./manifest.json';document.head.appendChild(link)}if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function hook(){const old=window.render;if(typeof old==='function'&&!window.__promptProRender){window.render=function(){const r=old.apply(this,arguments);setTimeout(()=>{promptUI();renderPromptsPro(document.querySelector('#proPromptBar .g')?.dataset.cat||'সব');templateUI()},0);return r};window.__promptProRender=true}promptUI();templateUI();pwa()}
Object.assign(window,{renderTemplatesPro,proFavPrompt,proUsePrompt,proCopyPrompt,proCopyText,proTemplateForm});window.addEventListener('DOMContentLoaded',()=>setTimeout(hook,250));
})();
