(()=>{const M={task:'tasks',prompt:'prompts',note:'notes',customer:'customers',due:'dues',template:'templates'};const $=id=>document.getElementById(id),T=()=>new Date().toISOString().slice(0,10),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast2(s){if(typeof toast==='function')toast(s)}
function upgradeSave(){window.saveM=async function(){let x={};if(mt==='task')x={title:val('f1')||'Quick Task',date:val('f2')||T(),priority:val('f3')||'Medium',note:val('f4')||'',done:ed?.done||false};if(mt==='prompt')x={title:val('f1')||'Quick Prompt',text:val('f2')||'',cat:val('f3')||''};if(mt==='note')x={title:val('f1')||'Quick Note',text:val('f2')||'',pinned:ed?.pinned||false};if(mt==='customer')x={name:val('f1')||'Unnamed Customer',phone:val('f2')||'',address:val('f3')||''};if(mt==='due')x={customer:val('f1')||'Unknown',phone:val('f2')||'',amount:+val('f3')||0,paid:ed?.paid||0,payDate:val('f4')||'',note:val('f5')||'',history:ed?.history||[]};if(mt==='template')x={title:val('f1')||'Untitled Template',text:val('f2')||''};if(mt==='prompt'&&!x.text)return toast2('Prompt লিখুন');if(mt==='note'&&!x.text)return toast2('নোট লিখুন');if(mt==='due'&&!x.amount)return toast2('টাকার পরিমাণ দিন');if(await put(mt,x,ed?.id)){closeM();render();toast2('Cloud-এ Save হয়েছে ✓')}}}
function addTemplates(){if(!data.templates)data.templates=[];let nav=document.querySelector('nav');if(!nav.querySelector('[data-v=templates]')){let b=document.createElement('button');b.dataset.v='templates';b.innerHTML='📋 <span>Templates</span>';b.onclick=()=>{view='templates';document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderUpgrade()};nav.appendChild(b)}
let s=document.getElementById('settings');if(s&&!s.querySelector('#backupBox'))s.insertAdjacentHTML('beforeend','<div id="backupBox" style="margin-top:18px;padding-top:15px;border-top:1px solid #dfe8e3"><h3>🛡️ Data Tools</h3><p class="muted">নিজের data এক ক্লিকে backup/restore করতে পারবেন।</p><button class="btn b" onclick="backupData()">Export Backup</button> <button class="btn l" onclick="document.getElementById(\'restoreFile\').click()">Restore Backup</button><input id="restoreFile" type="file" accept="application/json" hidden onchange="restoreData(this.files[0])"></div>')}
window.backupData=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sabuj-workdesk-backup-'+T()+'.json';a.click();toast2('Backup file তৈরি হয়েছে')};
window.restoreData=async f=>{if(!f)return;try{let x=JSON.parse(await f.text());for(let k of Object.keys(M))for(let v of x[M[k]]||[])await put(k,v,v.id);await load();toast2('Backup restore হয়েছে ✓')}catch(e){toast2('Backup file সঠিক নয়')}}}
function renderUpgrade(){if(view!=='templates')return;document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));let sec=document.getElementById('templatesView')||document.createElement('section');sec.id='templatesView';sec.className='view on';let q=(document.getElementById('tplq')?.value||'').toLowerCase();let a=(data.templates||[]).filter(x=>(x.title+' '+x.text).toLowerCase().includes(q));sec.innerHTML='<div class="card"><div class="toolbar"><input id="tplq" placeholder="Template খুঁজুন..." oninput="renderUpgrade()"><button class="btn g" onclick="openM(\'template\')">＋</button></div>'+ (a.map(x=>`<div class="row"><div><b>${E(x.title)}</b><small>${E(x.text)}</small></div><div class="ra"><button class="btn b" onclick='navigator.clipboard.writeText(${JSON.stringify(x.text)});toast("Template copied ✓")'>Copy</button><button class="btn l" onclick="openM('template',data.templates.find(a=>a.id=='${x.id}'))">Edit</button><button class="btn r" onclick="del('templates','${x.id}')">Delete</button></div></div>`).join('')||'<div class="empty">কোনো Template নেই</div>')+'</div>';document.getElementById('app').querySelector('main').appendChild(sec);document.getElementById('ttl').textContent='Templates'}
function promptEnhance(){let sec=document.getElementById('prompts');if(!sec)return;let tb=sec.querySelector('.toolbar');if(tb&&!tb.querySelector('#quickPrompt')){let b=document.createElement('button');b.id='quickPrompt';b.className='btn b';b.textContent='⚡ Quick';b.onclick=()=>quickPrompt();tb.appendChild(b)} }
window.quickPrompt=()=>{let q=prompt('Prompt search / keyword');if(q===null)return;let ps=document.getElementById('ps');if(ps){ps.value=q;document.querySelector('nav button[data-v=prompts]')?.click();render();setTimeout(()=>document.querySelector('#pl .btn.b')?.focus(),100)}};
function keyboard(){document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();quickPrompt()}if(e.key==='Escape')try{closeM()}catch{}})}
function patchModal(){let old=window.modal;window.modal=function(t,o=null){t=M[t]||t;if(t==='template'){mt='template';ed=o;document.getElementById('mh').textContent=(o?'Edit ':'নতুন ')+'Template';document.getElementById('mb').innerHTML='<div class="field"><label>Template name (ইচ্ছাধীন)</label><input id="f1" value="'+E(o?.title)+'" placeholder="যেমন: CV Format"></div><div class="field"><label>Content</label><textarea id="f2" style="min-height:180px">'+E(o?.text)+'</textarea></div>';document.getElementById('m').classList.add('on');return}old(t,o)}}
window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{try{upgradeSave();addTemplates();promptEnhance();keyboard();patchModal();}catch(e){console.error('upgrade',e)}},50));
})();